ktor:
  application:
    modules:
      - baranfit.ir.ApplicationKt.module
  deployment:
    port: 443

  security:
    ssl:
      keyStore: "/etc/letsencrypt/live/baranfit.ir/privkey.pem"
      keyAlias: sampleAlias
      keyStorePassword: 123
      privateKeyPassword: 123
