name: Build, Test, and Release Ktor App4

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the JAR file
      - name: Build JAR
        run: ./gradlew clean jar

      # Upload the JAR as an artifact (optional for debugging)
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ktor-app-jar
          path: build/libs/*.jar

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      # Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      # Create Release and Upload JAR
      - name: Create Release and Upload JAR
        run: |
          gh release create ${{ github.ref_name }} build/libs/*.jar \
            --title "Release ${{ github.ref_name }}" \
            --notes "This is an automated release for ${{ github.ref_name }}"
